package com.tap.DAOImple;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import com.tap.DAO.OrderDAO;
import com.tap.Model.Order;
import com.tap.Model.OrderItem;
import com.tap.Utility.DBConnection;

public class OrderDAOImple implements OrderDAO {

    @Override
    public void addOrder(Order order) {
        String query = "INSERT INTO orders (userId, restaurantId, totalAmount, status) VALUES (?, ?, ?, ?)";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement pstmt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS)) {
            
            pstmt.setInt(1, order.getUserId());
            pstmt.setInt(2, order.getRestaurantId());
            pstmt.setDouble(3, order.getTotalAmount());
            pstmt.setString(4, order.getStatus());
            pstmt.executeUpdate();
            
            // Get the ID generated by MySQL and set it to the order object
            try (ResultSet rs = pstmt.getGeneratedKeys()) {
                if (rs.next()) {
                    order.setOrderId(rs.getInt(1));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void addOrderItem(OrderItem item) {
        String query = "INSERT INTO orderitem (orderId, menuId, quantity, itemTotal) VALUES (?, ?, ?, ?)";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement pstmt = con.prepareStatement(query)) {
            
            pstmt.setInt(1, item.getOrderId());
            pstmt.setInt(2, item.getMenuId());
            pstmt.setInt(3, item.getQuantity());
            pstmt.setDouble(4, item.getItemTotal());
            pstmt.executeUpdate();
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public Order getOrder(int orderId) {
        String query = "SELECT * FROM orders WHERE orderId = ?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement pstmt = con.prepareStatement(query)) {
            pstmt.setInt(1, orderId);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) return extractOrder(rs);
        } catch (SQLException e) { e.printStackTrace(); }
        return null;
    }

    @Override
    public void updateOrderStatus(int orderId, String status) {
        
        // ADDED TRAP HERE: This will print immediately when the method is called
        System.out.println("DAO HIT! Running SQL for Order ID: " + orderId + " to Status: " + status);
        
        String query = "UPDATE orders SET status = ? WHERE orderId = ?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement pstmt = con.prepareStatement(query)) {
            pstmt.setString(1, status);
            pstmt.setInt(2, orderId);
            pstmt.executeUpdate();
            
            // OPTIONAL: Add a success trap!
            System.out.println("DAO SUCCESS! Database updated.");
            
        } catch (SQLException e) { 
            e.printStackTrace(); 
            // OPTIONAL: Add an error trap!
            System.out.println("DAO ERROR! Something went wrong in the SQL.");
        }
    }
    @Override
    public void deleteOrder(int orderId) {
        String query = "DELETE FROM orders WHERE orderId = ?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement pstmt = con.prepareStatement(query)) {
            pstmt.setInt(1, orderId);
            pstmt.executeUpdate();
        } catch (SQLException e) { e.printStackTrace(); }
    }

    @Override
    public List<Order> getAllOrders() {
        return fetchList("SELECT * FROM orders", null);
    }

    @Override
    public List<Order> getOrdersByUserId(int userId) {
        return fetchList("SELECT * FROM orders WHERE userId = ?", userId);
    }

    @Override
    public List<Order> getOrdersByRestaurantId(int restaurantId) {
        return fetchList("SELECT * FROM orders WHERE restaurantId = ?", restaurantId);
    }

    // Helper method to reduce code repetition
    private List<Order> fetchList(String sql, Integer param) {
        List<Order> list = new ArrayList<>();
        try (Connection con = DBConnection.getConnection();
             PreparedStatement pstmt = con.prepareStatement(sql)) {
            if (param != null) pstmt.setInt(1, param);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) list.add(extractOrder(rs));
        } catch (SQLException e) { e.printStackTrace(); }
        return list;
    }

    private Order extractOrder(ResultSet rs) throws SQLException {
        Order o = new Order();
        o.setOrderId(rs.getInt("orderId"));
        o.setUserId(rs.getInt("userId"));
        o.setRestaurantId(rs.getInt("restaurantId"));
        o.setTotalAmount(rs.getDouble("totalAmount"));
        o.setStatus(rs.getString("status"));
        o.setOrderDate(rs.getTimestamp("orderDate"));
        return o;
    }
}